name: Payroll Service - Build & Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'payroll-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'payroll-service/**'
  workflow_dispatch: {}

jobs:
  ci:
    uses: ./.github/workflows/_reusable-dotnet-build.yml
    with:
      service_name: payroll-service
      project_path: payroll-service/payroll-service.csproj
      test_project_path: ""
      dockerfile_path: ./payroll-service/Dockerfile
      context_path: ./payroll-service
      dotnet_version: '8.0.x'
      image_name: payroll-service
      trivy_scan_ref: payroll-service
      enable_sonar: ${{ vars.SONAR_ORGANIZATION != '' }}
      enable_slack_notify: true
      fail_on_critical_vuln: false
    secrets: inherit
